### PR TITLE
Fix switching languages at root

### LINKED ISSUE #625: Switching languages does not work properly
**Describe the bug**
When I switch language from English to Arabic and then switching back it keeps using Arabic.

**To Reproduce**

1. Go to [dzcode.io](https://www.dzcode.io)
2. Click on language button `English`
3. Scroll down to `Arabic`
4. Click on it and the website will be refreshed with Arabic
5. Click on language button `Arabic`
6. Click on `English`
7. Website is refreshed but it keeps using Arabic language (even after clicking many times)

**Expected behavior**
Switching languages should be seamless without any problems.

**Environment:**

- OS: MacOS
- Browser : Safari / Chrome

### PR DESCRIPTION
**Pull request by omdxp**
Fixes #625 

- [x] Bug fix
- [ ] New feature
- [ ] Other

### CODE REVIEW

File: web/src/redux/actions/settings.ts [hunk 1]
```diff
@@ -25,7 +21,7 @@ export const changeLanguage = async (languageCode: Language["code"]): Promise<vo
 
   // remove code from url if it's the default language
   if (language.code === Languages[0].code) {
-    newPath = newPath.replace(`/${language.code}`, "");
+    newPath = newPath.replace(new RegExp(`^/${language.code}`), "") || "/";
```
Comment (ZibanPirate) [inline web/src/redux/actions/settings.ts:24]: The regex is redundant, lets remove it

`/en` will always be the first match, and since we're not using `replaceAll`, this will only replace the first match `/en` occurrence, which is guaranteed to be the start of the URL because of the if block we're in

**Review by ZibanPirate — CHANGES_REQUESTED** [review]

**Review by ZibanPirate — APPROVED** [review]
